### ISSUE TITLE
Joined effort with openPDF?

### ISSUE THREAD

**Issue by Lonzak** [albfernandez/itext2#14]
Hi Alberto,

I just stumbled over your iText fork. I also maintain a (non-public) iText fork and I see that we have done lots of similar stuff :-)
I wanted to publish my fork too, but then I stumbled over the openPDF project (https://github.com/LibrePDF/OpenPDF). Why don't we join forces over there? I also saw that your are already a contributor there.
Any reason for still keeping your fork?

Regards,
Lonzak

**Comment by albfernandez** [comment]
Currently this fork is almost inactive.
The only reason to keep it alive is it's 100% backwards compatible with old itext.
Really I only take some important (and easy) changes to OpenPDF and put it here.
