### ISSUE TITLE
License type

### ISSUE THREAD

**Issue by cibik** [albfernandez/itext2#16]
plese, could detail on what are the license conditions to use the library? Readme specifies MPL/LGPL, while the attached LICENSE file contains only LGPL 3.0. Does it mean that MPL is not applicable? Or are the license conditions anyhow different? 

Thanks in advance for information. The unclear re-use conditions are making a mess in delivery of our own software :)

**Comment by albfernandez** [comment]
It's dual LGPL/MPL as itext 2.1.17 is.

I will clarify license  and readme.

**Comment by cibik** [comment]
Thanks for quick action. Appreciate it!
